import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowRight, faDumbbell } from '@fortawesome/free-solid-svg-icons';
import { useAuth } from '../context/AuthContext.jsx';

function AuthForm({ register = false }) {
  const { user, login, register: createAccount } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to={user.role === 'ADMIN' ? '/admin' : '/member'} replace/>;
  async function submit(event) { event.preventDefault(); setError(''); setBusy(true); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form); if (register && data.password !== data.confirmPassword) { setError('Your passwords do not match.'); setBusy(false); return; } try { const account = register ? await createAccount(data) : await login(data); navigate(account.role === 'ADMIN' ? '/admin' : '/member'); } catch (requestError) { setError(requestError.response?.data?.message || 'We could not complete that request. Please try again.'); } finally { setBusy(false); } }
  return <main className="auth-page"><div className="auth-photo"><div className="auth-photo-overlay"/><span className="auth-brand"><FontAwesomeIcon icon={faDumbbell}/> FITZONE</span><div><span className="eyebrow">Train strong. Live strong.</span><h2>Good things<br/>start with showing up.</h2><p>Find your next session and your people.</p></div><small>FICTIONAL DEMO STUDIO · NORTHBRIDGE</small></div><section className="auth-content"><Link className="auth-back" to="/">← Back to the studio</Link><div className="auth-box"><span className="eyebrow">{register ? 'Your next chapter' : 'Welcome back'}</span><h1>{register ? 'Create your account.' : 'Good to see you.'}</h1><p>{register ? 'A few details and you are ready to get moving.' : 'Sign in to pick up where you left off.'}</p><form className="form-panel auth-form" onSubmit={submit}>{register && <label>Full name<input name="name" required maxLength="80" autoComplete="name"/></label>}<label>Email address<input name="email" type="email" required autoComplete="email"/></label>{register && <label>Phone number<input name="phone" type="tel" required pattern="[+0-9() .-]{7,20}" autoComplete="tel"/></label>}<label>Password<input name="password" type="password" minLength="8" required autoComplete={register ? 'new-password' : 'current-password'}/></label>{register && <label>Confirm password<input name="confirmPassword" type="password" minLength="8" required autoComplete="new-password"/></label>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary" disabled={busy}>{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'} <FontAwesomeIcon icon={faArrowRight}/></button></form><p className="auth-switch">{register ? 'Already a member?' : 'New to FitZone?'} <Link to={register ? '/login' : '/register'}>{register ? 'Sign in' : 'Create an account'}</Link></p><small>Demo project · Never use a real password on a demo site.</small></div></section></main>;
}
export function Login() { return <AuthForm/>; }
export function Register() { return <AuthForm register/>; }
