import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBars, faBell, faCalendarCheck, faChartLine, faChevronLeft, faDumbbell, faEnvelope, faHouse, faIdCard, faPeopleGroup, faRightFromBracket, faUsers, faXmark } from '@fortawesome/free-solid-svg-icons';
import { useState } from 'react';
import { useAuth } from '../context/AuthContext.jsx';

const memberLinks = [['Overview','/member',faHouse],['My profile','/member/profile',faIdCard],['Membership','/member/membership',faIdCard],['Bookings','/member/bookings',faCalendarCheck],['Programs','/member/programs',faDumbbell],['Trainers','/member/trainers',faPeopleGroup],['Timetable','/member/timetable',faCalendarCheck],['Notifications','/member/notifications',faBell]];
const adminLinks = [['Overview','/admin',faHouse],['Members','/admin/members',faUsers],['Trainers','/admin/trainers',faPeopleGroup],['Programs','/admin/programs',faDumbbell],['Memberships','/admin/memberships',faIdCard],['Bookings','/admin/bookings',faCalendarCheck],['Enquiries','/admin/enquiries',faEnvelope],['Timetable','/admin/timetable',faCalendarCheck],['Testimonials','/admin/testimonials',faChartLine],['Contact messages','/admin/contact',faEnvelope],['FAQs','/admin/faq',faBell]];
function DashboardFrame({ admin = false }) {
  const { user, logout } = useAuth(); const [menuOpen, setMenuOpen] = useState(false); const navigate = useNavigate(); const links = admin ? adminLinks : memberLinks;
  function signOut() { logout(); navigate('/'); }
  return <div className="dashboard-shell"><aside className={`dashboard-sidebar${menuOpen ? ' menu-open' : ''}`}><div className="dash-brand"><span className="brand-mark"><FontAwesomeIcon icon={faDumbbell}/></span><span>FITZONE<small>{admin ? 'STUDIO ADMIN' : 'MEMBER SPACE'}</small></span><button aria-label="Close menu" className="sidebar-close" onClick={() => setMenuOpen(false)}><FontAwesomeIcon icon={faXmark}/></button></div><p className="sidebar-label">{admin ? 'MANAGEMENT' : 'YOUR SPACE'}</p><nav>{links.map(([label, path, icon]) => <NavLink end={path === (admin ? '/admin' : '/member')} to={path} key={path} onClick={() => setMenuOpen(false)}><FontAwesomeIcon icon={icon}/>{label}</NavLink>)}</nav><button className="logout-button" onClick={signOut}><FontAwesomeIcon icon={faRightFromBracket}/> Sign out</button><div className="sidebar-foot">FITZONE FITNESS STUDIO<br/>TRAIN STRONG. LIVE STRONG.</div></aside><div className="dashboard-main"><header className="dashboard-topbar"><button aria-label="Open menu" className="sidebar-open" onClick={() => setMenuOpen(true)}><FontAwesomeIcon icon={faBars}/></button><button className="back-to-site" onClick={() => navigate('/')}><FontAwesomeIcon icon={faChevronLeft}/> Website</button><span className="topbar-spacer"/><span className="topbar-user"><span className="avatar">{user?.name?.slice(0,1).toUpperCase()}</span><span>{user?.name}<small>{admin ? 'Studio administrator' : 'FitZone member'}</small></span></span></header><div className="dashboard-content"><Outlet/></div></div>{menuOpen && <button aria-label="Close navigation overlay" className="sidebar-scrim" onClick={() => setMenuOpen(false)}/>}</div>;
}
export function MemberLayout() { return <DashboardFrame/>; }
export function AdminLayout() { return <DashboardFrame admin/>; }
